// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name)
VALUES ($1)
RETURNING uuid, name, created_at
`

type CreateItemRow struct {
	Uuid      pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateItem(ctx context.Context, name string) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem, name)
	var i CreateItemRow
	err := row.Scan(&i.Uuid, &i.Name, &i.CreatedAt)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT uuid, name, quantity, created_at, updated_at
FROM items
WHERE uuid = $1
`

type GetItemRow struct {
	Uuid      pgtype.UUID
	Name      string
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetItem(ctx context.Context, uuid pgtype.UUID) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, uuid)
	var i GetItemRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemQuantity = `-- name: GetItemQuantity :one
SELECT quantity
FROM items
WHERE uuid = $1
`

func (q *Queries) GetItemQuantity(ctx context.Context, uuid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getItemQuantity, uuid)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getItemQuantityConcurrable = `-- name: GetItemQuantityConcurrable :one
SELECT quantity
FROM items
WHERE uuid = $1
FOR UPDATE
`

func (q *Queries) GetItemQuantityConcurrable(ctx context.Context, uuid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getItemQuantityConcurrable, uuid)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getNItemsOffset = `-- name: GetNItemsOffset :many
SELECT uuid, name, quantity, created_at, updated_at
FROM items
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetNItemsOffsetParams struct {
	Limit  int32
	Offset int32
}

type GetNItemsOffsetRow struct {
	Uuid      pgtype.UUID
	Name      string
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetNItemsOffset(ctx context.Context, arg GetNItemsOffsetParams) ([]GetNItemsOffsetRow, error) {
	rows, err := q.db.Query(ctx, getNItemsOffset, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNItemsOffsetRow
	for rows.Next() {
		var i GetNItemsOffsetRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchItem = `-- name: PatchItem :one
UPDATE items
SET
    name = COALESCE($2, name),
    quantity = COALESCE($3, quantity),
    updated_at = now()
WHERE uuid = $1 
RETURNING uuid, name, quantity, created_at, updated_at
`

type PatchItemParams struct {
	Uuid     pgtype.UUID
	Name     *string
	Quantity *int32
}

type PatchItemRow struct {
	Uuid      pgtype.UUID
	Name      string
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) PatchItem(ctx context.Context, arg PatchItemParams) (PatchItemRow, error) {
	row := q.db.QueryRow(ctx, patchItem, arg.Uuid, arg.Name, arg.Quantity)
	var i PatchItemRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setItemQuantity = `-- name: SetItemQuantity :one
UPDATE items
SET quantity = $1, updated_at = now()
WHERE uuid = $2
RETURNING uuid, name, quantity, updated_at
`

type SetItemQuantityParams struct {
	Quantity int32
	Uuid     pgtype.UUID
}

type SetItemQuantityRow struct {
	Uuid      pgtype.UUID
	Name      string
	Quantity  int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetItemQuantity(ctx context.Context, arg SetItemQuantityParams) (SetItemQuantityRow, error) {
	row := q.db.QueryRow(ctx, setItemQuantity, arg.Quantity, arg.Uuid)
	var i SetItemQuantityRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}
