// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
