// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        int32
	Uuid      pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Quantity  int32
}

type SchemaMigration struct {
	Version string
}

type Transaction struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ItemID    pgtype.UUID
	Type      string
	Amount    int32
	Status    string
	Reason    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Role         string
	RefreshToken string
	CreatedAt    pgtype.Timestamptz
}
